name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      name: "Checkout sources"
    - uses: actions-rs/toolchain@v1
      name: "Setup rust toolchain"
      with:
        profile: minimal
        toolchain: nightly
        override: "true"
        components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
